### ISSUE TITLE
Add Node and Docker action

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/adonys.me#1]

**Comment by RishiKumarRay** [comment]
can you elaboarte this @adonyssantos

**Comment by adonyssantos** [comment]
@RishiKumarRay I still have no idea. I do this to learn.

**Comment by adonyssantos** [comment]
I wanna implement GitHub Actions in this project.

**Comment by adonyssantos** [comment]
> @adonyssantos i can help you with this, just tell me how this project runs locally

Installing the dependencies with `npm i` or `yarn` and then running `npm start` or `yarn start` is enough to run the project

You can see what I've done in the `workflows` folder. Although I haven't managed to get it to work yet.

The goal of the Docker action is to generate an image every time I PR or commit to the main branch.

The purpose of the Node action is to execute the `npm publish` command every time I PR or commit to the main branch so that it can be deployed with GH Pages.

**Comment by adonyssantos** [comment]
@RishiKumarRay I am using Conventional Commits to name the commits: https://github.com/conventional-commits/conventionalcommits.org
